# Generated by Django 5.1.2 on 2024-10-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Merchant_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('MID', models.CharField(blank=True, max_length=50)),
                ('Transaction_Id', models.CharField(blank=True, max_length=50, null=True)),
                ('Order_Id', models.CharField(blank=True, max_length=50, null=True)),
                ('Transaction_Date', models.DateField(blank=True, null=True)),
                ('Settlement_Date', models.DateField()),
                ('Refund_Request_Date', models.DateField(blank=True, null=True)),
                ('Transaction_type', models.CharField(blank=True, max_length=50)),
                ('Gross_Amount', models.FloatField(blank=True, null=True)),
                ('Aggregator_Com', models.FloatField(blank=True, null=True)),
                ('Acquirer_Comm', models.FloatField(blank=True, null=True)),
                ('Payable_Merchant', models.FloatField(blank=True)),
                ('Payout_from_Nodal', models.FloatField(blank=True, null=True)),
                ('BankName_Receive_Funds', models.CharField(blank=True, max_length=50, null=True)),
                ('Nodal_Account_No', models.CharField(blank=True, max_length=50, null=True)),
                ('Aggregator_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Acquirer_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Refund_Flag', models.CharField(blank=True, max_length=10, null=True)),
                ('Payments_Type', models.CharField(blank=True, max_length=50, null=True)),
                ('MOP_Type', models.CharField(blank=True, max_length=50, null=True)),
                ('Credit_Debit_Date', models.DateField(blank=True, null=True)),
                ('Bank_Name', models.CharField(blank=True, max_length=15, null=True)),
                ('Refund_Order_Id', models.CharField(blank=True, max_length=50, null=True)),
                ('Acq_Id', models.CharField(blank=True, max_length=125, null=True)),
                ('Approve_code', models.CharField(blank=True, max_length=50, null=True)),
                ('Arn_No', models.CharField(blank=True, max_length=150, null=True)),
                ('Card_No', models.CharField(blank=True, max_length=150, null=True)),
                ('Tid', models.CharField(blank=True, max_length=125, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('Bank_Ref_id', models.CharField(blank=True, max_length=125, null=True)),
                ('File_upload_Date', models.DateTimeField(blank=True, null=True)),
                ('User_name', models.CharField(blank=True, max_length=25, null=True)),
                ('Recon_Status', models.CharField(blank=True, max_length=25, null=True)),
                ('Mpr_Summary_Trans', models.CharField(blank=True, max_length=10, null=True)),
                ('Merchant_code', models.CharField(blank=True, max_length=50, null=True)),
                ('Rec_Fmt', models.CharField(blank=True, max_length=50, null=True)),
                ('Card_type', models.CharField(blank=True, max_length=100, null=True)),
                ('Intl_Amount', models.FloatField(blank=True, null=True)),
                ('Domestic_Amount', models.FloatField(blank=True, null=True)),
                ('UDF1', models.CharField(blank=True, max_length=300, null=True)),
                ('UDF2', models.CharField(blank=True, max_length=300, null=True)),
                ('UDF3', models.CharField(blank=True, max_length=300, null=True)),
                ('UDF4', models.CharField(blank=True, max_length=300, null=True)),
                ('UDF5', models.CharField(blank=True, max_length=300, null=True)),
                ('UDF6', models.CharField(blank=True, max_length=300, null=True)),
                ('GST_Number', models.CharField(blank=True, max_length=50, null=True)),
                ('Credit_Debit_Amount', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['Order_Id', 'Transaction_Id'], name='upload_tran_Order_I_4dda07_idx')],
            },
        ),
    ]
